services:
  - type: web
    name: srm-welkin-atl-inventory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: FLASK_ENV 
        value: production 